alerting:
  enabled: true
  alert_rules:
    - name: Stopped Containers Greater than 0
      expr: count(container_last_seen{instance=~".*", image!=""}) - count(container_start_time_seconds{instance=~".*", image!=""}) > 0
      for: 1s
      evaluation_interval: 10s  # Ensure alerts are evaluated every 10 seconds
      labels:
        team: monitoring
        severity: critical
      annotations:
        summary: "Stopped Containers Alert"
        description: "The number of stopped containers is greater than 0. This indicates that there are containers that were running but have stopped. Please check the container status and logs."
      contact_point: email-contact

