global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        - '54.221.188.251:9100'
        - '3.91.27.225:9100'
        - '172.31.18.188:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - 'cadvisor:8080'
        - '54.221.188.251:8080'
        - '3.91.27.225:8080'
        - '172.31.18.188:8080'
