global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        - '<SERVER_ONE_IP>:9100'
        - '<SERVER_TWO_IP>:9100'
        - '<SERVER_THREE_IP>:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - 'cadvisor:8080'
        - '<SERVER_ONE_IP>:8080'
        - '<SERVER_TWO_IP>:8080'
        - '<SERVER_THREE_IP>:8080'
